config:
  - changed-files:
      - any-glob-to-any-file: 'internal/config/**'

framer:
  - changed-files:
      - any-glob-to-any-file: 'internal/framer/**'

module:
  - changed-files:
      - any-glob-to-any-file: 'internal/module/**'

processor:
  - changed-files:
      - any-glob-to-any-file: 'internal/processor/**'

routing:
  - changed-files:
      - any-glob-to-any-file: 'internal/route/**'
      - any-glob-to-any-file: 'router*'

cli:
  - changed-files:
      - any-glob-to-any-file: 'cmd/showbridge/**'
