changelog:
  exclude:
    authors:
      - dependabot
    labels:
      - dependencies
  categories:
    - title: Config ⚙️
      labels:
        - config
    - title: Framer 🖼️
      labels:
        - framer
    - title: Module 📦
      labels:
        - module
    - title: Processor 🏭
      labels:
        - processor
    - title: Routing 🛣️
      labels:
        - router
        - route
    - title: CLI ⌨️
      labels:
        - cli
    - title: Other Changes
      labels:
        - "*"
