api:
  enabled: true
  port: 8080
modules:
  - id: http
    type: http.server
    params:
      port: 3000
  - id: udp
    type: net.udp.client
    params:
      host: 127.0.0.1
      port: 8000
routes:
  - input: http
    id: http-to-osc
    processors:
      - id: create-osc
        type: osc.message.create
        params:
          address: "{{.Payload.URL.Path}}"
      - id: encode-osc
        type: osc.message.encode
      - id: output-osc
        type: module.output
        params:
          module: udp
